name: Deploy Static Website

on:
  push:
    branches:
      - main  # or 'master' if your default branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Root directory containing index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
